version: "3.8"

services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: regulatory-chatbot-chromadb
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    volumes:
      - chromadb_data:/chroma/chroma
    restart: unless-stopped

  # Optional: MongoDB if you want to run it locally
  mongodb:
    image: mongo:latest
    container_name: regulatory-chatbot-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  chromadb_data:
  mongodb_data:
